name: Terraform Workflow

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7

      - name: Terraform files
        run: |
           cd terraform
           ls
           sed -i 's/default\s*=\s*1/default = 2/' variables2.tf
           terraform init
           terraform plan
