name: Terraform Workflow

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.5

      - name: Change directory to Terraform files
        run: |
           cd terraform
           ls

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform
        run: terraform output -auto-approve
