name: Scale Service

on:
  workflow_dispatch:
    inputs:
      test_region:
        required: true 
        type: string
        description: The aws region where the scaling happen.
      aws_account_alias:
        required: true 
        type: string
        description: The aws account alias where the scaling happen.
      
jobs:
  scale-service:
    runs-on: ubuntu-latest
    env:
      AWS_ACCOUNT : ${{ inputs.aws_account_alias }}
      REGION : ${{ inputs.test_region }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: AWS Account Alias
        id: aws_account_alias
        run: |
          echo "This is AWS ACCOUNT ---> ${{ env.AWS_ACCOUNT }} "
          NEW_AWS_ACCOUNT=$(echo "${{ env.AWS_ACCOUNT }}_siffix")

          echo "Original AWS ACCOUNT ---> ${{ env.AWS_ACCOUNT }}"
          echo "New AWS ACCOUNT ---> $NEW_AWS_ACCOUNT"

      - name: Print New AWS Account
        env:
          NEW_AWS_ACCOUNT: ${{ steps.aws_account_alias.outputs.NEW_AWS_ACCOUNT }}
        run: |     
          echo "Value of NEW_AWS_ACCOUNT ---> $NEW_AWS_ACCOUNT"
