name: Terraform Workflow 2

# env:
#   # TF_VAR_is_secondary_region_active: true
#   TF_VAR_is_secondary_region_active: "true"

on:
  workflow_dispatch:
    inputs:
      is_secondary_region_active:
        default: 'false'
        required: true
        type: boolean


jobs:
  terraform:
    # if: ${{ needs.create-change-request.outputs.is_secondary_region_active == 'True'}}
    runs-on: ubuntu-latest
    # env:
    #   TF_VAR_is_secondary_region_active: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7

      - name: Terraform files
        run: |
           cd infrastructure/instance/
           ls
           rm terraform-dev.auto.tfvars
           echo 'is_secondary_region_active = True' >> terraform-dev.auto.tfvars
           cat terraform-dev.auto.tfvars
           ls
           # sed -i 's/default\s*=\s*false/default = true/' variable.tf
           terraform init
           terraform plan

  terraform2:
    # if: ${{ needs.create-change-request.outputs.is_secondary_region_active == 'True'}}
    runs-on: ubuntu-latest
    # env:
    #   TF_VAR_is_secondary_region_active: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7

      - name: Terraform files
        run: |
           cd infrastructure/instance/
           ls
           # sed -i 's/default\s*=\s*false/default = true/' variable.tf
           terraform init
           terraform plan
