name: Terraform CI

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.7

      - name: Apply Terraform
        run: |
          terraform init
          terraform apply -auto-approve
        env:
          TF_VAR_example_variable: ${{ secrets.EXAMPLE_VARIABLE }}
